## This notebook represents a relatively unstructured exploration into my biometric data. For nice plots, see the plots folder or the pretty_plots.ipynb for code

In [2]:
import pandas as pd
import xml.etree.ElementTree as et
import polars as pl
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from astral import moon
import datetime as dt
import os
os.chdir('/Users/christiantapp/Library/Mobile Documents/com~apple~CloudDocs/code/apple-heart-rate')

### Preprocessing, memory optimization

In [3]:
# tree = et.parse(r"C:\Users\Christian\code_projects\health\apple_health_export\export.xml")
# root = tree.getroot()
# records = []

# for record in root.findall('Record'):
#     record_data = {
#         'type': record.attrib.get('type'),
#         'unit': record.attrib.get('unit'),
#         'value': record.attrib.get('value'),
#         'sourceName': record.attrib.get('sourceName'),
#         'sourceVersion': record.attrib.get('sourceVersion'),
#         'device': record.attrib.get('device'),
#         'creationDate': record.attrib.get('creationDate'),
#         'startDate': record.attrib.get('startDate'),
#         'endDate': record.attrib.get('endDate')
#     }
#     records.append(record_data)

# apple_data = pd.DataFrame(records)
# print(apple_data.info())
# apple_data.type = apple_data.type.astype('category')
# apple_data.unit = apple_data.unit.astype('category')
# apple_data.value = pd.to_numeric(apple_data.value, errors='coerce')
# apple_data.sourceName = apple_data.sourceName.astype('category')
# apple_data.device = apple_data.device.astype('category')
# apple_data.creationDate = pd.to_datetime(apple_data.creationDate).dt.tz_localize(None)
# apple_data.startDate = pd.to_datetime(apple_data.startDate).dt.tz_localize(None)
# apple_data.endDate = pd.to_datetime(apple_data.endDate).dt.tz_localize(None)
# print(apple_data.info())
# apple_data.to_feather("data/apple_health.feather")

In [4]:
apple_data = pd.read_feather("data/apple_health.feather")

In [5]:
apple_data.query('type == "HKQuantityTypeIdentifierHeartRate"')

,type,unit,value,sourceName,sourceVersion,device,creationDate,startDate,endDate
115,HKQuantityTypeIdentifierHeartRate,count/min,60.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301661810>, name:Apple Watch, ma...",2024-01-13 01:08:23,2024-01-13 01:03:52,2024-01-13 01:03:52
116,HKQuantityTypeIdentifierHeartRate,count/min,61.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301661810>, name:Apple Watch, ma...",2024-01-13 01:13:55,2024-01-13 01:09:54,2024-01-13 01:09:54
117,HKQuantityTypeIdentifierHeartRate,count/min,65.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301661810>, name:Apple Watch, ma...",2024-01-13 11:49:36,2024-01-13 01:16:15,2024-01-13 01:16:15
118,HKQuantityTypeIdentifierHeartRate,count/min,70.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301661810>, name:Apple Watch, ma...",2024-01-13 11:55:00,2024-01-13 11:50:54,2024-01-13 11:50:54
119,HKQuantityTypeIdentifierHeartRate,count/min,82.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301661810>, name:Apple Watch, ma...",2024-01-13 11:59:21,2024-01-13 11:59:20,2024-01-13 11:59:20
...,...,...,...,...,...,...,...,...,...
474040,HKQuantityTypeIdentifierHeartRate,count/min,68.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301685130>, name:Apple Watch, ma...",2024-09-06 11:50:33,2024-09-06 11:45:27,2024-09-06 11:45:27
474041,HKQuantityTypeIdentifierHeartRate,count/min,67.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301685130>, name:Apple Watch, ma...",2024-09-06 11:55:29,2024-09-06 11:51:02,2024-09-06 11:51:02
474042,HKQuantityTypeIdentifierHeartRate,count/min,67.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301685130>, name:Apple Watch, ma...",2024-09-06 12:00:20,2024-09-06 11:56:34,2024-09-06 11:56:34
474043,HKQuantityTypeIdentifierHeartRate,count/min,70.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301685130>, name:Apple Watch, ma...",2024-09-06 12:07:09,2024-09-06 12:00:08,2024-09-06 12:00:08
474044,HKQuantityTypeIdentifierHeartRate,count/min,55.0,Christian’s Apple Watch,8.7.1,"<<HKDevice: 0x301685130>, name:Apple Watch, ma...",2024-09-06 12:12:12,2024-09-06 12:07:30,2024-09-06 12:07:30

In [6]:
all_metrics = apple_data[apple_data.type.str.contains('heart|step|stand|mass',case=False)].copy().sort_values(by='startDate').reset_index(drop=True)
del apple_data

In [7]:
all_metrics.type.unique().tolist()

['HKQuantityTypeIdentifierStepCount',
 'HKCategoryTypeIdentifierAppleStandHour',
 'HKQuantityTypeIdentifierWalkingHeartRateAverage',
 'HKQuantityTypeIdentifierRestingHeartRate',
 'HKQuantityTypeIdentifierHeartRate',
 'HKQuantityTypeIdentifierBodyMass',
 'HKQuantityTypeIdentifierHeartRateVariabilitySDNN',
 'HKCategoryTypeIdentifierHighHeartRateEvent',
 'HKQuantityTypeIdentifierAppleStandTime',
 'HKQuantityTypeIdentifierWalkingStepLength',
 'HKQuantityTypeIdentifierBodyMassIndex']

## Now that's a lot of heartbeats! How can I dive deeper...

In [8]:
heart_rate = all_metrics.query('type == "HKQuantityTypeIdentifierHeartRate"').copy()
heart_rate_fig = px.line(heart_rate[heart_rate.startDate >= pd.to_datetime('2024-07-01')], x = 'startDate',y = 'value')
heart_rate_fig

### I just realized, I take my watch off when I sleep. By looking "between" the heart rate data, I have a pretty decent estimate of my sleep pattern for the past 7 years

In [9]:
#extracting sleep times like this give you the date of morning after sleep
heart_rate['measurement_gap'] = heart_rate.startDate.diff()
heart_rate['inferred_sleep'] = heart_rate.measurement_gap > pd.Timedelta(hours=4)
inferred_sleep = heart_rate[heart_rate.inferred_sleep == True][['startDate','measurement_gap']].copy().reset_index(drop=True)
inferred_sleep = inferred_sleep.assign(
    hours_of_sleep = inferred_sleep.measurement_gap.dt.total_seconds() / 3600,
    #this provides the date of previous day, when sleep started
    sleep_date = inferred_sleep.startDate - pd.Timedelta(days=1)
    )
inferred_sleep = inferred_sleep.rename(columns = {'startDate':'woke_up_date'})

inferred_sleep['day_of_week'] = inferred_sleep.sleep_date.dt.day_name()

#remove some outliers, i don't think i slept more than 15 hours
inferred_sleep = inferred_sleep[inferred_sleep.hours_of_sleep < 15].reset_index(drop=True)
inferred_sleep['std_dev'] = inferred_sleep.hours_of_sleep.rolling(window = 60).std()
inferred_sleep['avg_sleep'] = inferred_sleep.hours_of_sleep.rolling(window = 60).mean()

# color scale for the days of the week if I need them
color_dict = {'Monday':'blue', 'Tuesday':'orange', 'Wednesday':'green', 'Thursday':'red', 'Friday':'purple', 'Saturday':'black', 'Sunday':'gray'}
inferred_sleep['day_color'] = inferred_sleep.day_of_week.map(color_dict)

In [10]:
sleep_chart = make_subplots()

for day in inferred_sleep.day_of_week.unique():
    sleep_chart.add_trace(go.Scatter(x=inferred_sleep.sleep_date[inferred_sleep.day_of_week == day], y=inferred_sleep.hours_of_sleep[inferred_sleep.day_of_week == day], mode='markers', name=day))
sleep_chart.add_trace(go.Scatter(x=inferred_sleep.sleep_date, y=inferred_sleep.std_dev, mode='lines', line=dict(width=3), name='Rolling Bi-Monthly Std. Deviation'))
sleep_chart.add_trace(go.Scatter(x=inferred_sleep.sleep_date, y=inferred_sleep.avg_sleep, mode='lines', line=dict(width=2, color = 'black'), name='Rolling Bi-Monthly Mean'))
sleep_chart.update_layout(
    xaxis = dict(title = "Date", range = [pd.to_datetime('2017-12-24'), pd.to_datetime('2024-10-01')]),
    yaxis = dict(title = "Hours of sleep", range = [0, 18], dtick = 2),
    title = "Inferred Sleep From Heart Rate Gaps",
)

In [13]:
len(inferred_sleep)

2415

In [11]:
#inferred_sleep.to_feather('data/inferred_sleep.feather')

## Moon Phase, Heart Rate, and Sleep
 Bear with me here. This paper discusses the influence moon phase has on heart rate: https://doi.org/10.1007/s00484-012-0605-z. What am I supposed to not see for myself??
 Curious to see if there is any correlation of my own heart rate with moon phase (the paper only claims heart rate recovery and peak HR differ between phases, but not resting)

more papers: https://pmc.ncbi.nlm.nih.gov/articles/PMC7840136/ https://www.health.harvard.edu/staying-healthy/moonlight-may-affect-sleep-cycles (moon phase and sleep length)

In [12]:
def get_moon_phase(date):
    phase_dict = {
    range(0, 7): "new_moon",
    range(7, 14): "first_quarter",
    range(14, 21): "full_moon",
    range(21, 28): "last_quarter"
    }
    for num_range,phase_name in phase_dict.items():
        if int(moon.phase(date)) in num_range:
            return phase_name



heart_rate['moon_phase'] = heart_rate.startDate.apply(get_moon_phase)

In [13]:
heart_rate['year'] = heart_rate.startDate.dt.year
#heart_rate.to_feather('data/heart_rate.feather')
avg_rates_phase = heart_rate[heart_rate.value < 80].groupby(['moon_phase','year']).value.mean().reset_index()

In [14]:
resting_heart = all_metrics[all_metrics.type.str.contains('resting',case=False)].copy().reset_index(drop=True)
resting_heart['moon_phase'] = resting_heart.startDate.apply(get_moon_phase)
resting_heart['year'] = resting_heart.startDate.dt.year
#resting_heart.to_feather('data/resting_heart.feather')
avg_resting_per_phase = resting_heart.groupby(['moon_phase','year']).value.mean().reset_index()

 Hmm, underwhelming but expected results. 
 However, I wasn't expecting to see such a dip in resting heart rate during 2021! This coincided with the pandemic of course, which happens to be when I began boxing regularly

In [15]:
moon_phase_palette = {
    'first_quarter':'#333399', 
    'full_moon': '#ccccff',  
    'last_quarter':'#666699', 
    'new_moon':'#000033',
}
resting_moon_fig = go.Figure()
for phase,color in moon_phase_palette.items():
    phase_data = avg_resting_per_phase.query(f'moon_phase == "{phase}"')
    resting_moon_fig.add_trace(go.Bar(
        x=phase_data.query('year != 2017').year, 
        y=phase_data.query('year != 2017').value, 
        name=phase,
        marker_color = color))

resting_moon_fig.update_layout(
    title = "Average Resting Heart Rate by Moon Phase",
    barmode = "group",
    xaxis = dict(title = "Year"),
    yaxis = dict(
        title = "Average Resting Heart Rate (BPM)", 
        range = [53,63],
        dtick = 2),
    legend = dict(title = 'Moon Phase')
    )
    
resting_moon_fig

In [18]:
avg_resting_per_phase

       moon_phase  year      value
0   first_quarter  2017  63.333333
1   first_quarter  2018  58.068182
2   first_quarter  2019  60.067416
3   first_quarter  2020  56.051546
4   first_quarter  2021  53.781609
5   first_quarter  2022  55.431818
6   first_quarter  2023  57.510417
7   first_quarter  2024  57.661290
8       full_moon  2018  58.861702
9       full_moon  2019  60.900000
10      full_moon  2020  54.851064
11      full_moon  2021  54.554348
12      full_moon  2022  56.056180
13      full_moon  2023  57.044944
14      full_moon  2024  57.327869
15   last_quarter  2018  58.784946
16   last_quarter  2019  60.892473
17   last_quarter  2020  55.241379
18   last_quarter  2021  55.302083
19   last_quarter  2022  55.428571
20   last_quarter  2023  56.573034
21   last_quarter  2024  57.000000
22       new_moon  2017  71.000000
23       new_moon  2018  58.639535
24       new_moon  2019  60.000000
25       new_moon  2020  55.034483
26       new_moon  2021  53.577778
27       new_moon  2022  56.156250
28       new_moon  2023  57.032967
29       new_moon  2024  56.950820

## Wake Time By Day Of Week

In [16]:
inferred_sleep['wake_time'] = inferred_sleep.woke_up_date.dt.time
inferred_sleep

,woke_up_date,measurement_gap,hours_of_sleep,sleep_date,day_of_week,std_dev,avg_sleep,day_color,wake_time
0,2017-12-26 11:35:10,0 days 11:08:19,11.138611,2017-12-25 11:35:10,Monday,NaN,NaN,blue,11:35:10
1,2017-12-27 11:28:13,0 days 11:03:32,11.058889,2017-12-26 11:28:13,Tuesday,NaN,NaN,orange,11:28:13
2,2017-12-28 12:16:39,0 days 10:56:46,10.946111,2017-12-27 12:16:39,Wednesday,NaN,NaN,green,12:16:39
3,2017-12-29 11:44:15,0 days 09:21:21,9.355833,2017-12-28 11:44:15,Thursday,NaN,NaN,red,11:44:15
4,2017-12-30 12:08:49,0 days 11:24:41,11.411389,2017-12-29 12:08:49,Friday,NaN,NaN,purple,12:08:49
...,...,...,...,...,...,...,...,...,...
2410,2024-09-02 10:49:07,0 days 11:32:11,11.536389,2024-09-01 10:49:07,Sunday,1.427962,9.880778,gray,10:49:07
2411,2024-09-03 10:16:16,0 days 09:23:35,9.393056,2024-09-02 10:16:16,Monday,1.429183,9.875556,blue,10:16:16
2412,2024-09-04 10:25:39,0 days 09:23:36,9.393333,2024-09-03 10:25:39,Tuesday,1.430459,9.865731,orange,10:25:39
2413,2024-09-05 10:52:44,0 days 10:16:29,10.274722,2024-09-04 10:52:44,Wednesday,1.426304,9.857065,green,10:52:44
2414,2024-09-06 10:39:40,0 days 09:39:00,9.650000,2024-09-05 10:39:40,Thursday,1.420158,9.836537,red,10:39:40

In [17]:
def hours_since_midnight(time):
    hours = time.hour
    minutes = time.minute
    seconds = time.second
    return hours + minutes/60 + seconds/3600


inferred_sleep['wake_time_in_hours'] = inferred_sleep.wake_time.apply(hours_since_midnight)
inferred_sleep['year'] = inferred_sleep.sleep_date.dt.year

In [18]:
wake_time_fig = px.violin(inferred_sleep, x = 'day_of_week', y = 'wake_time_in_hours', animation_frame='year', range_y=[0,18])
wake_time_fig

In [23]:
inferred_sleep.drop(columns=['avg_sleep','day_color','wake_time_in_hours','measurement_gap']).to_csv('/Users/christiantapp/Library/Mobile Documents/com~apple~CloudDocs/code/javascript/vite-blog/frontend/public/sleep_data.csv',index=False)